using RapidERP.Application.DTOs.CountryDTOs;

namespace RapidERP.Application.CQRS.CountryModule.Command.CountryLocalizationCommands.UpdateCountryLocalization;

public record UpdateCountryLocalizationCommand(CountryLocalizationPUT localization);
