using RapidERP.Application.DTOs.CountryDTOs;

namespace RapidERP.Application.CQRS.CountryModule.Command.CountryLocalizationCommands.CreateCountryLocalization;

public record CreateCountryLocalizationCommand(CountryLocalizationPOST localization);