using RapidERP.Application.DTOs.MainModuleDTOs;

namespace RapidERP.Application.Features.MainModuleFeatures.CreateSingleCommand;

public record CreateSingleMainModuleCommandRequestModel(MainModulePOST masterPOST);