using RapidERP.Application.DTOs.MessageModuleDTOs;

namespace RapidERP.Application.Features.MessageModuleFeatures.CreateSingleCommand;

public record CreateSingleMessageModuleCommandRequestModel(MessageModulePOST masterPOST);
